/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
/**
 *
 * @author lloyd
 */
public class numberOfPlayerWindow extends javax.swing.JFrame {

    /**
     * Creates new form numberOfPlayerWindow
     */
    public numberOfPlayerWindow() {
        initComponents();
        EventListener listenerd = new EventListener();
        twoPlayersButton.addActionListener(listenerd);
        threePlayersButton.addActionListener(listenerd);
        fourPlayersButton.addActionListener(listenerd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberOfPlayersLabel = new javax.swing.JLabel();
        twoPlayersButton = new javax.swing.JButton();
        threePlayersButton = new javax.swing.JButton();
        fourPlayersButton = new javax.swing.JButton();
        playerNameTextFeild = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        enterAPlayersNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numberOfPlayersLabel.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        numberOfPlayersLabel.setForeground(new java.awt.Color(255, 0, 0));
        numberOfPlayersLabel.setText("How Many Player Are There?");

        twoPlayersButton.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        twoPlayersButton.setForeground(new java.awt.Color(0, 0, 204));
        twoPlayersButton.setText("Two");

        threePlayersButton.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        threePlayersButton.setForeground(new java.awt.Color(0, 0, 204));
        threePlayersButton.setText("Three");

        fourPlayersButton.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        fourPlayersButton.setForeground(new java.awt.Color(0, 0, 204));
        fourPlayersButton.setText("Four");

        playerNameTextFeild.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N

        submitButton.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        submitButton.setForeground(new java.awt.Color(0, 0, 204));
        submitButton.setText("Submit");

        enterAPlayersNameLabel.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        enterAPlayersNameLabel.setForeground(new java.awt.Color(255, 0, 0));
        enterAPlayersNameLabel.setText("Enter A Players Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerNameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(submitButton)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOfPlayersLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(twoPlayersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(threePlayersButton)
                        .addGap(78, 78, 78)
                        .addComponent(fourPlayersButton)
                        .addGap(181, 181, 181))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterAPlayersNameLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(numberOfPlayersLabel)
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoPlayersButton)
                    .addComponent(threePlayersButton)
                    .addComponent(fourPlayersButton))
                .addGap(90, 90, 90)
                .addComponent(enterAPlayersNameLabel)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void chooseNumbers(){
        enterAPlayersNameLabel.setVisible(false);
        playerNameTextFeild.setVisible(false);
        submitButton.setVisible(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(numberOfPlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(numberOfPlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(numberOfPlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(numberOfPlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new numberOfPlayerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterAPlayersNameLabel;
    private javax.swing.JButton fourPlayersButton;
    private javax.swing.JLabel numberOfPlayersLabel;
    private javax.swing.JTextField playerNameTextFeild;
    private javax.swing.JButton submitButton;
    private javax.swing.JButton threePlayersButton;
    private javax.swing.JButton twoPlayersButton;
    // End of variables declaration//GEN-END:variables
    
public ArrayList<String> players = new ArrayList<String>();
    
    private class EventListener implements ActionListener{
        public void actionPerformed(ActionEvent i){
            if (i.getSource() == twoPlayersButton){
                for(int j = 0; j < 2; j++){
                    if(i.getSource() == submitButton){
                     
                    }
                }
                numberPlayerButtonsActionPerformed();
            }
            else if (i.getSource() == threePlayersButton){
                for(int k = 0; k < 3; k++){
                    
                }
                numberPlayerButtonsActionPerformed();
            }
            else if (i.getSource() == fourPlayersButton){
                for(int l = 0; l < 4; l++){
                    
                }
                numberPlayerButtonsActionPerformed();
            }
        }
    }
    
    private void numberPlayerButtonsActionPerformed(){
        this.setVisible(false);
        gamePlayWindow j = new gamePlayWindow();
        j.setVisible(true);
    }

}
