/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author lloyd
 */
public class startUpWindow extends javax.swing.JFrame {

    /**
     * Creates new form startUpWindow
     */
    public startUpWindow() {
        initComponents();
        EventListener listener = new EventListener();                       //Add event listeners for all the buttons
        startNewGameButton.addActionListener(listener);
        rulesButton.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        startNewGameButton = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Boundary");
        setBackground(new java.awt.Color(255, 255, 255));

        titleLabel.setFont(new java.awt.Font("Arial", 3, 60)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 0, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("BOUNDARY");

        startNewGameButton.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        startNewGameButton.setForeground(new java.awt.Color(0, 0, 204));
        startNewGameButton.setText("Start New Game");

        rulesButton.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        rulesButton.setForeground(new java.awt.Color(0, 0, 204));
        rulesButton.setText("Rules");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(rulesButton)
                .addContainerGap(320, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startNewGameButton)
                .addGap(249, 249, 249))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(titleLabel)
                .addGap(107, 107, 107)
                .addComponent(startNewGameButton)
                .addGap(18, 18, 18)
                .addComponent(rulesButton)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startUpWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startUpWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton startNewGameButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

    private class EventListener implements ActionListener{
       public void actionPerformed(ActionEvent e){
            if (e.getSource() == startNewGameButton){             // If the player clicks the startNewGameButton,
                goToPlayerNameWindow();                             // go to the game mode window.
            }    
            else if (e.getSource() == rulesButton){               // If the player clicks the rulesButton,
                goToRulesWindow();                                // go to the rules window.
            }
        }
    }
    
    private void goToPlayerNameWindow(){                         // Function to go to the player name window
        this.setVisible(false);
        playerNameWindow s = new playerNameWindow();
        s.setVisible(true);
    }
    
    private void goToRulesWindow(){                             // Function to go to the rules window
        this.setVisible(false);
        rulesWindow b = new rulesWindow();
        b.setVisible(true);
    }

}
